name = "cluba"
main = ".open-next/worker.js"
compatibility_date = "2026-03-08"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "KV_BINDING"
id = "49fe3c898c2f4a84af1c5e6cd51db62b"
